---

- name: --- install Chrony ---
  yum:
    name: "{{ item }}"
    state: present
  with_items:
       - "chrony"
       
- name: --- config Chrony ---
  template: src=chrony-config.j2 dest=/etc/chrony.conf

- name: --- start chrony service ---
  service:
    name: chronyd
    state: started




